Repository Sparta-bootcamp-master-4team/WeatherApp, pull requests merged in 2025-05, with the labels that each got.

#3 Feat/location search model layer
  WeatherApp/WeatherApp.xcodeproj/project.pbxproj
  WeatherApp/WeatherApp/Common/Extensions/Bundle+Keys.swift
  WeatherApp/WeatherApp/Data/Repositories/GeocodingRepository.swift
  WeatherApp/WeatherApp/Data/Service/GeocodingService.swift
  WeatherApp/WeatherApp/Domain/Entities/Location.swift
  WeatherApp/WeatherApp/Domain/Interfaces/Repositories/GeocodingRepositoryProtocol.swift
  WeatherApp/WeatherApp/Domain/Interfaces/UseCases/FetchCoordinateUseCaseProtocol.swift
  WeatherApp/WeatherApp/Domain/Interfaces/UseCases/FetchCoordinatesUseCaseProtocol.swift
  WeatherApp/WeatherApp/Domain/Interfaces/UseCases/SearchDongsUseCaseProtocol.swift
  WeatherApp/WeatherApp/Domain/UseCases/FetchCoordinateUseCase.swift
  WeatherApp/WeatherApp/Domain/UseCases/FetchCoordinatesUseCase .swift
  WeatherApp/WeatherApp/Domain/UseCases/SearchDongsUseCase.swift
  WeatherApp/WeatherApp/Resources/dongList.json
Labels: enhancement

#7 Feat/network
  WeatherApp/WeatherApp/Data/Repositories/WeatherRepository.swift
  WeatherApp/WeatherApp/Data/Service/WeatherAPIService.swift
  WeatherApp/WeatherApp/Domain/Entities/CurrentWeather.swift
  WeatherApp/WeatherApp/Domain/Entities/DailyWeather.swift
  WeatherApp/WeatherApp/Domain/Entities/HourlyWeather.swift
  WeatherApp/WeatherApp/Domain/Entities/TemperatureInfo.swift
  WeatherApp/WeatherApp/Domain/Entities/WeatherDescription.swift
  WeatherApp/WeatherApp/Domain/Entities/WeatherResponse.swift
  WeatherApp/WeatherApp/Domain/Interfaces/Repositories/WeatherRepositoryProtocol.swift
  WeatherApp/WeatherApp/Domain/Interfaces/UseCases/FetchAllWeatherUseCaseProtocol.swift
  WeatherApp/WeatherApp/Domain/Interfaces/UseCases/FetchCurrentWeatherUseCaseProtocol.swift
  WeatherApp/WeatherApp/Domain/Interfaces/UseCases/FetchDailyWeatherUseCaseProtocol.swift
  WeatherApp/WeatherApp/Domain/Interfaces/UseCases/FetchHourlyWeatherUseCaseProtocol.swift
  WeatherApp/WeatherApp/Domain/UseCases/FetchCurrentWeatherUseCase.swift
  WeatherApp/WeatherApp/Domain/UseCases/FetchDailyWeatherUseCase.swift
  WeatherApp/WeatherApp/Domain/UseCases/FetchHourlyWeatherUseCase.swift
  WeatherApp/WeatherApp/Domain/UseCases/FetchWeatherUseCase.swift
Labels: ✨Feature

#10 feat: 현재 위치 정보 받아오는 기능 구현
  WeatherApp/WeatherApp/Data/Repositories/LocationRepository.swift
  WeatherApp/WeatherApp/Data/Service/LocationService.swift
  WeatherApp/WeatherApp/Domain/Interfaces/Repositories/LocationRepositoryProtocol.swift
  WeatherApp/WeatherApp/Domain/Interfaces/UseCases/GetCurrentLocationUseCaseProtocol.swift
  WeatherApp/WeatherApp/Domain/UseCases/GetCurrentLocationUseCase.swift
  WeatherApp/WeatherApp/Resources/Info.plist
Labels: enhancement

#15 Feat/coordinate to address
  WeatherApp/WeatherApp/Data/Repositories/ReverseGeocodingRepository.swift
  WeatherApp/WeatherApp/Data/Service/GeocodingService.swift
  WeatherApp/WeatherApp/Data/Service/ReverseGeocodingService.swift
  WeatherApp/WeatherApp/Domain/Entities/Region.swift
  WeatherApp/WeatherApp/Domain/Interfaces/Repositories/ReverseGeocodingRepositoryProtocol.swift
  WeatherApp/WeatherApp/Domain/Interfaces/UseCases/ReverseGeocodingUseCaseProtocol.swift
  WeatherApp/WeatherApp/Domain/UseCases/ReverseGeocodingUseCase.swift
Labels: ✨Feature

#16 feat: Extension 확장
  WeatherApp/WeatherApp/Common/Extensions/Date+.swift
  WeatherApp/WeatherApp/Common/Extensions/DateFormatter+.swift
Labels: ✨Feature

#12 [Bug] 키보드 나타났을 때, 검색 테이블 뷰 아래쪽 가려짐
  WeatherApp/WeatherApp/Presentation/Search/View/Cell/SearchViewCell.swift
  WeatherApp/WeatherApp/Presentation/Search/View/SearchViewController.swift
Labels: bug

#20 [Feat] 검색 결과 없음 레이블 구현
  WeatherApp/WeatherApp/Presentation/Search/View/Cell/NoResultsView.swift
  WeatherApp/WeatherApp/Presentation/Search/View/SearchViewController.swift
Labels: ✨Feature

#18 feat: MainVC 관련 기초 UI 일부 구현
  WeatherApp/WeatherApp.xcodeproj/project.pbxproj
  WeatherApp/WeatherApp/App/SceneDelegate.swift
  WeatherApp/WeatherApp/Common/Extensions/UIFont+.swift
  WeatherApp/WeatherApp/Common/Extensions/UIStackView+.swift
  WeatherApp/WeatherApp/Common/Extensions/UIView+.swift
  WeatherApp/WeatherApp/Data/Service/ReverseGeocodingService.swift
  WeatherApp/WeatherApp/Domain/Entities/Region.swift
  WeatherApp/WeatherApp/Presentation/Main/View/MainDetailViewController.swift
  WeatherApp/WeatherApp/Presentation/Main/View/MainPageViewController.swift
  WeatherApp/WeatherApp/Presentation/Main/View/MainViewController.swift
  WeatherApp/WeatherApp/Presentation/Main/ViewModel/MainViewModel.swift
  WeatherApp/WeatherApp/Presentation/Main/ViewModel/PageViewModel.swift
  WeatherApp/WeatherApp/Resources/Assets.xcassets/Characters/Contents.json
  WeatherApp/WeatherApp/Resources/Assets.xcassets/Characters/clearSky.imageset/Contents.json
  WeatherApp/WeatherApp/Resources/Assets.xcassets/Characters/clearSky.imageset/clearSky.svg
  WeatherApp/WeatherApp/Resources/Assets.xcassets/Characters/clouds.imageset/Contents.json
  WeatherApp/WeatherApp/Resources/Assets.xcassets/Characters/clouds.imageset/clouds.svg
  WeatherApp/WeatherApp/Resources/Assets.xcassets/Characters/fewClouds.imageset/Contents.json
  WeatherApp/WeatherApp/Resources/Assets.xcassets/Characters/fewClouds.imageset/fewClouds.svg
  WeatherApp/WeatherApp/Resources/Assets.xcassets/Characters/mist.imageset/Contents.json
  WeatherApp/WeatherApp/Resources/Assets.xcassets/Characters/mist.imageset/mist.svg
  WeatherApp/WeatherApp/Resources/Assets.xcassets/Characters/rain.imageset/Contents.json
  WeatherApp/WeatherApp/Resources/Assets.xcassets/Characters/rain.imageset/rain.svg
  WeatherApp/WeatherApp/Resources/Assets.xcassets/Characters/showerRain.imageset/Contents.json
  WeatherApp/WeatherApp/Resources/Assets.xcassets/Characters/showerRain.imageset/showerRain.svg
  WeatherApp/WeatherApp/Resources/Assets.xcassets/Characters/snow.imageset/Contents.json
  WeatherApp/WeatherApp/Resources/Assets.xcassets/Characters/snow.imageset/snow.svg
  WeatherApp/WeatherApp/Resources/Assets.xcassets/Characters/thunderStorm.imageset/Contents.json
  WeatherApp/WeatherApp/Resources/Assets.xcassets/Characters/thunderStorm.imageset/thunderStorm.svg
  WeatherApp/WeatherApp/Resources/Assets.xcassets/Colors/Contents.json
  WeatherApp/WeatherApp/Resources/Assets.xcassets/Colors/customBlue.colorset/Contents.json
  WeatherApp/WeatherApp/Resources/Assets.xcassets/Colors/customGray.colorset/Contents.json
  WeatherApp/WeatherApp/Resources/Assets.xcassets/Colors/customRed.colorset/Contents.json
  WeatherApp/WeatherApp/Resources/Fonts/NanumSquareB.ttf
  WeatherApp/WeatherApp/Resources/Fonts/NanumSquareEB.ttf
  WeatherApp/WeatherApp/Resources/Fonts/NanumSquareL.ttf
  WeatherApp/WeatherApp/Resources/Fonts/NanumSquareR.ttf
  WeatherApp/WeatherApp/Resources/Info.plist
Labels: ✨Feature

#24 feat: 8일 중 최저온도와 최고온도를 반환해주는 UseCase 구현
  WeatherApp/WeatherApp.xcodeproj/project.pbxproj
  WeatherApp/WeatherApp/Domain/Entities/TemperatureRange.swift
  WeatherApp/WeatherApp/Domain/Interfaces/UseCases/FetchDailyTemperatureRangeUseCaseProtocol.swift
  WeatherApp/WeatherApp/Domain/UseCases/FetchDailyTemperatureRangeUseCase.swift
Labels: ✨Feature

#25 feat: CoreData를 이용한 CRD 구현
  WeatherApp/WeatherApp/Data/PersistentStorages/CoreData/Entity+CoreDataClass.swift
  WeatherApp/WeatherApp/Data/PersistentStorages/CoreData/Entity+CoreDataProperties.swift
  WeatherApp/WeatherApp/Data/PersistentStorages/CoreData/Model.xcdatamodeld/Model.xcdatamodel/contents
  WeatherApp/WeatherApp/Data/Repositories/CoreDataLocationRepository.swift
  WeatherApp/WeatherApp/Domain/Interfaces/Repositories/CoreDataLocationRepositoryProtocol.swift
  WeatherApp/WeatherApp/Domain/Interfaces/UseCases/DeleteLocationUseCaseProtocol.swift
  WeatherApp/WeatherApp/Domain/Interfaces/UseCases/FetchLocationsUseCaseProtocol.swift
  WeatherApp/WeatherApp/Domain/Interfaces/UseCases/SaveLocationUseCaseProtocol.swift
  WeatherApp/WeatherApp/Domain/UseCases/DeleteLocationUseCase.swift
  WeatherApp/WeatherApp/Domain/UseCases/FetchLocationsUseCase.swift
  WeatherApp/WeatherApp/Domain/UseCases/SaveLocationUseCase.swift
Labels: ✨Feature

#26 feat: 메인 뷰 내 컬렉션뷰 다중 섹션 기초 레이아웃 적용
  WeatherApp/WeatherApp.xcodeproj/project.pbxproj
  WeatherApp/WeatherApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WeatherApp/WeatherApp/App/SceneDelegate.swift
  WeatherApp/WeatherApp/Common/Extensions/UICollectionView+.swift
  WeatherApp/WeatherApp/Presentation/Main/View/MainDetailViewController.swift
  WeatherApp/WeatherApp/Presentation/Main/View/MainPageViewController.swift
  WeatherApp/WeatherApp/Presentation/Main/View/MainViewController.swift
  WeatherApp/WeatherApp/Presentation/Main/View/Section.swift
  WeatherApp/WeatherApp/Presentation/Main/View/Section/MainSectionModel.swift
  WeatherApp/WeatherApp/Presentation/Main/View/Section/SectionItem.swift
  WeatherApp/WeatherApp/Presentation/Main/ViewModel/MainDetailViewModel.swift
  WeatherApp/WeatherApp/Presentation/Main/ViewModel/MainViewModel.swift
Labels: ✨Feature

#27 [Feat] 리스트 뷰 UI, 뷰 모델, 바인딩 구현
  WeatherApp/WeatherApp.xcodeproj/project.pbxproj
  WeatherApp/WeatherApp/Presentation/List/View/Cell/ListViewCell.swift
  WeatherApp/WeatherApp/Presentation/List/View/ListView.swift
  WeatherApp/WeatherApp/Presentation/List/View/ListViewController.swift
  WeatherApp/WeatherApp/Presentation/List/ViewModel/ListViewModel.swift
  WeatherApp/WeatherApp/Presentation/Search/View/Cell/NoResultsView.swift
  WeatherApp/WeatherApp/Presentation/Search/View/SearchViewController.swift
Labels: ✨Feature

#32 feat: UseCase 일일(총8일)날씨 + 최고 최저온도 반환 구현
  WeatherApp/WeatherApp/Domain/Entities/DailyWeatherAndTemperaturnRange.swift
  WeatherApp/WeatherApp/Domain/Interfaces/UseCases/GetDailyWeatherAndTemperaturnRangeUseCaseProtocol.swift
  WeatherApp/WeatherApp/Domain/UseCases/GetDailyWeatherAndTemperaturnRangeUseCase.swift
Labels: ✨Feature

#31 [Feat] 리스트 뷰 UseCase 연동
  WeatherApp/WeatherApp/Presentation/List/View/ListViewController.swift
  WeatherApp/WeatherApp/Presentation/List/ViewModel/ListViewModel.swift
  WeatherApp/WeatherApp/Presentation/Protocol/ViewModelProtocol.swift
  WeatherApp/WeatherApp/Presentation/Search/View/SearchViewController.swift
  WeatherApp/WeatherApp/Presentation/Search/ViewModel/SearchViewModel.swift
Labels: ✨Feature

#52 [Refactor] 리스트 뷰, 검색 뷰
  WeatherApp/WeatherApp/Presentation/List/View/Cell/ListViewCell.swift
  WeatherApp/WeatherApp/Presentation/Search/View/Cell/NoResultsView.swift
  WeatherApp/WeatherApp/Presentation/Search/View/Cell/SearchViewCell.swift
  WeatherApp/WeatherApp/Presentation/Search/View/SearchView.swift
  WeatherApp/WeatherApp/Presentation/Search/View/SearchViewController.swift
Labels: refactor

#54 chore: README.md에 시연 영상 추가
  README.md
Labels: documentation
